import { EXCEPTION_NAMES, STATUS_NAMES, SUB_STATUS_NAMES } from '../types';

export const STATUS_FR: Record<number, string> = {
  0: 'Initialisation',
  1: 'Au repos',
  2: 'Impression',
  3: 'Chargement filament',
  4: 'Déchargement filament',
  5: 'Nivellement',
  6: 'Calibration PID',
  7: 'Test de résonance',
  8: 'Auto-diagnostic',
  9: 'Mise à jour',
  10: "Mise à l'origine",
  11: 'Transfert de fichier',
  12: 'Création du timelapse',
  13: 'Extrudeur en action',
  14: "Arrêt d'urgence",
  15: 'Reprise après coupure',
};

export const SUB_STATUS_FR: Record<number, string> = {
  1041: 'Environnement trop froid',
  1045: 'Préchauffe buse',
  1096: 'Refroidissement buse',
  1405: 'Préchauffe plateau',
  1906: 'Refroidissement plateau',
  1070: 'Refroidissement caisson',
  1071: 'Caisson refroidi',
  1072: 'Échec refroidissement caisson',
  1053: 'PID : préchauffe',
  1054: 'PID : mesure',
  1055: 'PID terminé',
  1056: 'PID en échec',
  1061: 'Chargement extrudeur',
  1062: 'Déchargement extrudeur',
  1063: 'Chargement terminé',
  1064: 'Déchargement terminé',
  1066: 'Changement de filament',
  1133: 'Chauffe buse',
  1134: 'Insérer le filament',
  1135: 'Saisie du filament',
  1136: 'Filament saisi',
  1143: 'Coupe du filament',
  1144: 'Éjection du filament',
  1145: 'Filament éjecté',
  1150: 'Canvas : début chargement',
  1151: 'Canvas : chauffe buse',
  1152: 'Canvas : insertion',
  1153: 'Canvas : coupe',
  1154: 'Canvas : rétraction',
  1155: 'Canvas : alimentation',
  1156: 'Canvas : purge',
  1157: 'Canvas : chargé',
  1158: 'Canvas : échec chargement',
  1160: 'Canvas : début déchargement',
  1161: 'Canvas : chauffe buse',
  1162: 'Canvas : vérification',
  1163: 'Canvas : coupe',
  1164: 'Canvas : rétraction',
  1165: 'Canvas : déchargé',
  1166: 'Canvas : échec déchargement',
  2075: 'Impression',
  2077: 'Impression terminée',
  2401: 'Reprise',
  2402: 'Reprise effectuée',
  2405: 'Reprise après coupure',
  2406: 'Reprise après coupure effectuée',
  2501: 'Mise en pause',
  2502: 'En pause',
  2503: 'Arrêt en cours',
  2504: 'Arrêtée',
  2505: 'Filament interrompu',
  2601: 'Mise à jour : infos',
  2603: 'Initialisation terminée',
  2701: 'Mise à jour : téléchargement',
  2702: 'Mise à jour : extraction',
  2703: 'Mise à jour : écriture',
  2704: 'Mise à jour terminée',
  2705: 'Mise à jour en échec',
  2801: "Mise à l'origine",
  2802: 'Origine faite',
  2901: 'Nivellement',
  2902: 'Nivellement terminé',
  3000: 'Envoi du fichier',
  3001: 'Fichier envoyé',
  3010: 'Copie du fichier',
  3011: 'Fichier copié',
  3020: 'Timelapse : traitement',
  3021: 'Timelapse prêt',
  3022: 'Timelapse en échec',
  5932: 'Accéléromètre OK',
  5933: 'Accéléromètre en erreur',
  5934: 'Optimisation résonance',
  5935: 'Résonance terminée',
  5936: 'Résonance en échec',
};

export const EXCEPTION_FR: Record<number, string> = {
  101: 'Chauffe plateau en échec',
  102: 'Sonde plateau déconnectée',
  103: 'Chauffe buse en échec',
  104: 'Sonde buse déconnectée',
  105: 'Sonde buse en court-circuit',
  106: 'Sonde plateau en court-circuit',
  107: 'Surchauffe tête',
  108: 'Surchauffe plateau',
  109: 'Fin de filament',
  205: 'Sonde caisson déconnectée',
  206: 'Sonde caisson en court-circuit',
  304: 'Origine Z en échec',
  401: 'Accéléromètre en erreur',
  605: 'Capteur de pression en erreur',
  701: 'Ventilateur carte mère',
  702: 'Ventilateur heatbreak',
  703: 'Ventilateur pièce',
  704: 'Nivellement en échec',
  705: 'Ventilateur auxiliaire',
  706: 'Ventilateur caisson',
  707: 'Capot ventilateur tête détaché',
  801: 'Communication carte / extrudeur',
  802: 'Communication capteur de nivellement',
  803: 'Erreur système critique',
  901: 'Caisson trop chaud',
  902: 'Surchauffe caisson',
  903: 'Surchauffe des drivers',
  904: 'Clé USB pleine',
  905: 'Lecture USB en erreur',
  906: 'Mise à jour en échec',
  1101: 'Ouverture ventilation en échec',
  1102: 'Fermeture ventilation en échec',
  1103: 'Servo de grille en échec',
  1104: 'Driver moteur Y',
  1105: 'Driver moteur Z',
  1106: 'Driver moteur extrudeur',
  1210: 'Communication Canvas',
  1211: 'Canvas : fin de filament',
  1220: "Canvas : filament anormal dans l'extrudeur",
  1231: 'Canvas : couteau non enfoncé',
  1232: 'Canvas : couteau non relâché',
  1241: "Canvas : capteur d'alimentation muet",
  1242: "Canvas : délai d'alimentation",
  1243: 'Canvas : alimentation bloquée',
  1244: 'Extrusion tête en échec',
  1251: 'Canvas : rétraction en échec (filament cassé)',
  1252: 'Canvas : délai de rétraction',
  1260: 'Canvas : fin de filament',
  1261: 'Capot avant de tête détaché',
  1262: 'Canvas : couteau en erreur',
  1263: 'Canvas : filament emmêlé',
  1264: 'Filament bloqué en amont',
  1300: "Fichier d'impression indisponible",
  1301: 'Spaghetti détecté',
  1302: "Défaut d'impression détecté",
};

export const SPEED_MODES = [
  { value: 0, label: 'Silence', pct: 50 },
  { value: 1, label: 'Équilibré', pct: 100 },
  { value: 2, label: 'Sport', pct: 130 },
  { value: 3, label: 'Ludicrous', pct: 160 },
] as const;

export function statusLabel(code: number | undefined): string {
  if (code === undefined) return '--';
  return STATUS_FR[code] ?? STATUS_NAMES[code] ?? `État ${code}`;
}

export function subStatusLabel(code: number | undefined): string {
  if (!code) return '';
  return SUB_STATUS_FR[code] ?? SUB_STATUS_NAMES[code] ?? `Sous-état ${code}`;
}

export function exceptionLabel(code: number): string {
  return EXCEPTION_FR[code] ?? EXCEPTION_NAMES[code] ?? `Erreur ${code}`;
}
